# Generated by Django 4.0.2 on 2022-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_order_options_order_order_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_choice',
            field=models.CharField(choices=[('1', 'Пакет 1'), ('2', 'Пакет 2'), ('3', 'Пакет 3')], default='1', max_length=20, verbose_name='Пакет'),
        ),
    ]
